/*! Code generated by Coframe AI Editor */
/*! Transpiled: 2025-11-27T18:37:44.302Z */
(()=>{var r=Symbol.for("JSX.Fragment");function i(t){let n=document.createElement("style");return n.textContent=t,document.head.appendChild(n),n}function o(){let t="https://cdn.coframe.com/assets/memoryair/Screenshot-2025-11-27-at-11.17.09-a.m.-d6dfd2c4-ab93-4cfb-8584-6d79294cd39f.webp",s=`
    #lp-pom-box-417 {
      background-image: url('${t}') !important;
      background-size: cover !important;
      background-position: center !important;
    }
    #lp-pom-image-120 img {
      object-fit: cover !important;
    }
  `;i(s);let e=document.querySelector("#lp-pom-image-120 img");e&&(e.src=t,e.srcset=`${t} 1x, ${t} 2x, ${t} 3x`,e.setAttribute("data-src-mobile-1x",t),e.setAttribute("data-src-mobile-2x",t),e.setAttribute("data-src-mobile-3x",t)),window.CFQ=window.CFQ||[],window.CFQ.push({emit:"variantRendered"})}try{o()}catch(t){console.error("Error applying variant:",t)}})();
