/*! Code generated by Coframe AI Editor */
/*! Transpiled: 2025-11-27T16:15:07.822Z */
(()=>{var n=Symbol.for("JSX.Fragment");var e=document.querySelector("section#hero-section h1.leading-trim.headline-xl.text-primaryReverse");e?(e.textContent="Smarter money. Smarter businesses.",window.CFQ=window.CFQ||[],window.CFQ.push({emit:"variantRendered"})):console.error("Headline element not found");})();
